### ISSUE TITLE
Amiga side don't start

### ISSUE THREAD

**Issue by romontic** [michalsc/Emu68#145]
Hi all, I have prepared an SD card following the tutorial https://github.com/michalsc/Emu68/blob/master/docs/tutorials/SD_Preparation.md 
After that I putted the SD in the Raspberyy/Pistorm over an A500, so emu68 started fine showing the emu68 logo through hdmi output on a TV set. Amiga side nothing happen, not video nor floppy drive.  Note that Pistorm + PiOS + Amiga.rom (without emu68) functions like a charm over the same set-up. What I have made wrong?

**Comment by GiR-Zippo** [comment]
The current version (fd3bd4ee0046aba0474eccbc600a44251ee431c6) is working fine with the PiStorm hardware (Max II).
But I'd used the diskpart directly without the Ui step (like here http://tech.webit.nu/pistorm-preparing-the-sd-card-for-emu68/ ), the only thing I changed was instead of building 4 partitions 
`cre part pri size=200
cre part pri size=500 id=76
cre part pri size=2000 id=76
cre part pri id=76`

I simply created only the Fat32 and the partition for the Amiga RDB.
`clean
cre part pri size=200
cre part pri size=500 id=76
cre part pri size=2000 id=76
cre part pri id=76
sel part 1
assign
format fs=FAT32 label=Emu68 quick`
After this I simply dropped the compiled files in the fat drive and that's it.
(btw, the old coffin r54 is working extremely nice with the Emu68)

**Comment by michalsc** [comment]
@romontic Apparently you have downloaded wrong version (-raspi) of Emu68 binaries. You should instead download the one which is meant for PiStorm, containing ``-pistorm-`` in the archive name.

**Comment by romontic** [comment]
Yes, Mich, my fail, I downloaded the wrong version.
Thank you very much

**Comment by michalsc** [comment]
I'm glad to hear that. So, I guess I will close this issue now. Enjoy using PiStorm and Emu68 :)
