### ISSUE TITLE
Is it hypervisor friendly?

### ISSUE THREAD

**Issue by SamuraiCrow** [michalsc/Emu68#3]
Just a comment about hypervisors:  According to a blog post about running Xen on ARM, software needs to be modified slightly to run under Xen or KVM on ARM8 clients.  If it could run independently of the other 5 cores of my PineBook Pro, it might reduce some of the driver support to a message pass to Arix or some similar ARM AROS derivative.

**Comment by michalsc** [comment]
At the moment I am not using hypervisor at all, and the entire Emu68 is running in supervisor mode only. Could you point me to the blog post you've mentioned?

**Comment by SamuraiCrow** [comment]
https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/virtualization-on-arm-with-xen

**Comment by michalsc** [comment]
Unfortunately the document does not describe details about adapting an operating system for work under hypervisor on aarch64, but rather necessary options to prepare proper linux kernel for it.

On the other hand, since qemu provides its "virt" machine meant explicitly for virtual environments, and since this version supports KVM acceleration on aarch64, this may be the good approach to check. I will investigate it and eventually add new target - virt64.
